name: Dev App Build

on:
  push:
    branches:
    - sonar_scanning

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: dev
        clean: 'true'
        token: '${{ secrets.GIT_TOKEN }}'
        submodules: 'recursive'
        fetch-depth: '0'
        
    # - name: Npm install
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 16.15.1
    # - run: npm install
        
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: command line 
      run: |
        pwd
        ls

    # - name: Sonar code analysis 
    #   uses: sonarsource/sonarqube-scan-action@master
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    # - name: Build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     push: true
    #     context: .
    #     file: Dockerfile
    #     tags: adminmindgrep/gs_service:dev

    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     image-ref: 'adminmindgrep/gs_service:dev'
    #     format: 'table'
    #     exit-code: '0'
    #     ignore-unfixed: true
    #     vuln-type: 'os,library'
    #     severity: 'LOW,MEDIUM,CRITICAL,HIGH'          