name: Manual App Build

on: 
  workflow_dispatch:
    inputs:
     gs_service_version:
        description: 'Gs_service version'
        required: true
        default: '0.0.1'
     branch:
        description: 'Branch'
        required: true
        default: 'master'        

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
        clean: 'true'
        token: '${{ secrets.GIT_TOKEN }}'
        submodules: 'recursive'
        fetch-depth: '0'
        
    - name: Npm install
      uses: actions/setup-node@v3
      with:
        node-version: 16.20.1

    - run: npm install
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: Dockerfile
        tags: adminmindgrep/gs_service:${{ github.event.inputs.gs_service_version }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'adminmindgrep/gs_service:${{ github.event.inputs.gs_service_version }}'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'LOW,MEDIUM,CRITICAL,HIGH'            

