name: Run Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - v2

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout gs-node-service
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run compile
        run: npm run build

      - name: Checkout test project
        uses: actions/checkout@v4
        with:
          repository: godspeedsystems/gs-test-project
          token: ${{ secrets.GIT_TOKEN }}
          path: gs-test-project
          ref: dev-test
      - name: Install project dependencies
        run: |
          cd gs-test-project  
          npm install
      - name: Run test-project test-suite
        run: |
          cd gs-test-project  
          npm run dev-test
